@startuml

!define _TITLE_ SoftModem
!define _PROJECT_CODE_ SoftModem
!define _LAST_MODIFIED_ 2015-02-02
!define _VERSION_ 0.1.1

class SoftModem {
    - observer
    + sharedInstance()
    - addObserver()
    - removeObserver()
    - start(@NotNull String challenge)
    - stop()
}
interface SoftModemListener {
    - onDetectedPlug()
    - onReceivedSerialNumber(@NotNull String serialNumber, @NotNull String plugVersion)
    ..
    - onReceivedResponse:(@NotNull String* response, @NotNull String serialNumber, @NotNull String plugVersion, @NotNull String challenge)
    ..
    ' called when softmodem can't detect plug for some reasons. (timeout/failed)
    - onReceivedPlugDetectionError(SoftModemError error)
    ' called when softmodem can't receive serial number for some reasons. (timeout/failed)
    - onReceivedSerialNumberError(SoftModemError error)
    ' called when softmodem can't receive response for some reasons.
    - onReceivedResponseError(SoftModemError error)
}
enum SoftModemError {
    TIMEOUT
    INVALID
}

class Modulator {
    - AudioOutput output
    - String challengeString
    - sendCharge()
    - sendChallenge()

    - start()
    - stop()
}
class Demodulator {
    - start()
    - stop()
}
interface DemodulatorListener {
    - onDetectedPlug()
    - onReceivedSerialNumber(String serialNumber, String plugVersion)
    - onReceivedResponse(String response)
    - onReceivedPlugDetectionError()
    - onReceivedSerialNumberError()
    - onReceivedResponse()
}
class AudioConfig {
    + plugAirInput(float sampleRate)
    + plugAirOutput(float sampleRate)
}

' Custom AudioTrack Class
class AudioInput {
    - startFetchingAudio()
    - stopFetchingAudio()
}
' Custom AudioRecord Class
class AudioOutput {
    - startPlayback()
    - stopPlayback()
}

Modulator "1" - "1" SoftModem : > send signal to
Modulator "1" -- "1" AudioOutput
DemodulatorListener <|-- SoftModem
SoftModem "1" - "1" Demodulator : < invoke event handler to
Demodulator "1" -- "1" AudioInput

class NativeManager {
    + sharedManager()
    + sendSignal()
    + receiveSignal()

    ' called from sendSignal() via AudioOutput
    - com_beatrobo_library_softmodem_NativeManager_push()
    - com_beatrobo_library_softmodem_NativeManager_pull()
}



@enduml